- hosts: local
  gather_facts: no

  tasks:
    - name: display encrypted values (for demo only!)
      debug:
        msg:
        - "API Key: {{ api_key }}"
        - "DB Password: {{ db_password }}"
        - "Secret Token: {{ vault_secret_token }}"
